version: '2'
services:
  jaeger:
    image: jaegertracing/all-in-one:0.8.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686/tcp"
      - "14268:14268/tcp"
      - "9411:9411/tcp"
    networks:
      - mynetwork

  redis:
    image: redis:6.2.6-alpine
    networks:
      - mynetwork

  flaskapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080/tcp"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
